### ISSUE TITLE
Add/edit emails is broken

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/EDD-Conditional-Emails#1]
When saving a new email, you get redirected back to the All Downloads screen. The URL is: `/wp-admin/edit.php?post_type=download#038;page=edd-settings&#038;tab=emails#edd-conditional-emails-table`

When I go back to the Downloads > Settings > Email screen, this is what I see:

![image](https://cloud.githubusercontent.com/assets/1254870/10149125/9062702c-6605-11e5-94bf-4d8dd06bc6cd.png)

If I edit that email, this is what I see:

![image](https://cloud.githubusercontent.com/assets/1254870/10149139/a35007e4-6605-11e5-880b-c6abc097fbb5.png)

If I try to fix the subject that wasn't saved from the first attempt, I get redirected back to the All Downloads screen again and the subject is not saved and the condition still says "Condition unknown".

Happens with just EDD 2.4.6 and latest Conditional Emails activated.

[Customer reported here](https://secure.helpscout.net/conversation/125623059/17683/).

Ping @ghost1227. Can you fix this up quickly? It's basically not functional like this.

**Comment by ghost1227** [comment]
On it!

**Comment by ghost1227** [comment]
Fixed ages ago... https://github.com/easydigitaldownloads/EDD-Conditional-Emails/commit/18007c3c6d7c04f0cb9935f5c7903ec36474f7a9
