### ISSUE TITLE
Update plugin header author and pass ID in updater

### ISSUE THREAD

**Issue by mihaijoldis** [easydigitaldownloads/EDD-Conditional-Emails#12]
Update plugin header author
Pass ID in the updater function and also update the Author

**Comment by ashleyfae** [comment]
> The latest version is in branch 1.1.1 so that might need to be merged in master.

Where are you seeing that?

**Comment by ashleyfae** [comment]
Yeah I just mean that `master` here also shows `1.1.1` as the latest version: https://github.com/easydigitaldownloads/EDD-Conditional-Emails/blob/master/edd-conditional-emails.php#L6 So I guess I wasn't sure what you thought should be merged into master.
