### ISSUE TITLE
add support for Checkout Fields Manager email tags

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/EDD-Conditional-Emails#3]
EDD core supports CFM email tags based on {meta_key} values. Conditional Emails should do the same.

**Comment by pippinsplugins** [comment]
@SDavisMedia I'm not sure I understand what should be supported here. Could you elaborate?

**Comment by SDavisMedia** [comment]
@pippinsplugins If you add a field to the checkout form using Checkout Fields Manager, you can use its meta key value as an email tag in EDD's core emails.

Conditional Emails gives you some flexibility with who you can send emails to and for specific reasons... just an extension of EDD's core email sending functionality. But it does not support CFM's custom fields by using the {meta_key_value} like EDD core does.

**Comment by pippinsplugins** [comment]
AH! Yes, makes sense.

**Comment by pippinsplugins** [comment]
@ghost1227

**Comment by ghost1227** [comment]
I need a copy of CFM to make this happen. It doesn't appear to be on Github (or at least I don't have access to it)

**Comment by SDavisMedia** [comment]
@chriscct7 Can you hook that up? ^^^

**Comment by chriscct7** [comment]
All of mine are on GitHub: https://github.com/chriscct7/edd-checkout-fields/

**Comment by pippinsplugins** [comment]
@chriscct7 Can you make sure @ghost1227 has access to those?

**Comment by chriscct7** [comment]
He does. He was the first added to the repo according to GitHub.

**Comment by ghost1227** [comment]
Got it! I was looking under the EDD organization *glares at @chriscct7*

**Comment by ghost1227** [comment]
Added in 1.1.0
