### ISSUE TITLE
Support sending email when payment is pending

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Conditional-Emails#4]
We need to support sending an email when a purchase is set to pending. We advertise this as a feature on the plugin's page and only just now discovered that it's not possible.

**Comment by ghost1227** [comment]
I'm confused...

![](http://cloud.section214.com/0u1E0O3r1Q2i/Image%202016-01-08%20at%2010.57.10%20AM.png])

**Comment by pippinsplugins** [comment]
@ghost1227 Try it. It doesn't work.

**Comment by ghost1227** [comment]
![](http://cloud.section214.com/441a331E3Z0u/Image%202016-01-08%20at%2011.15.43%20AM.png)

**Comment by pippinsplugins** [comment]
Can you show me a full screenshot of your settings?

**Comment by ghost1227** [comment]
![](http://cloud.section214.com/0a2W3R1x1G40/Image%202016-01-08%20at%204.33.35%20PM.png)

**Comment by pippinsplugins** [comment]
@ghost1227 Are you changing a payment from Complete to Pending? That's not what we need. We need to support sending a payment when it's initially created as `Pending`. In that case it's gone from nothing to `Pending`.

**Comment by pippinsplugins** [comment]
Works great.
