### ISSUE TITLE
New condition: License upgrade & renewals

### ISSUE THREAD

**Issue by flowdee** [easydigitaldownloads/EDD-Conditional-Emails#6]
Would be amazing to get support for EDD Software Licensing and email customers after they made a license upgrade or renewal.

This way it would be possible to increase customer loyalty by saying thank your for their transaction and/or offer special deals/discounts etc.

**Comment by ghost1227** [comment]
Support for emails on license upgrade is added in 1.1.0, along with a few corresponding email tags. Currently, there's no actions during the renewal process, but I'm looking into adding them.

**Comment by flowdee** [comment]
@pippinsplugins possible to get an action to hook in renewals?

**Comment by pippinsplugins** [comment]
Just use `edd_complete_purchase` and detect if renewal:
```php
$was_renewal = edd_get_payment_meta( $payment_id, '_edd_sl_is_renewal', true );
```

**Comment by ghost1227** [comment]
oh duh...

**Comment by flowdee** [comment]
Thanks @pippinsplugins, amazing support!

Well ghost, would be great to get the renewal feature as well 😄

**Comment by ghost1227** [comment]
Already added!

**Comment by flowdee** [comment]
Awesome! great work @ghost1227 👍
